package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * ChickenStrips class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class ChickenStrips implements Item {
    /**
     * Initial cost of ChickenStrips.
     */
    static final int INITIAL_COST = 250000;
    private double cost;
    private double passiveValue;
    private int count;
    /**
     * Constructs an object of type ChickenStrips.
     */
    public ChickenStrips() {
        this.cost = INITIAL_COST;
        this.passiveValue = 0;
        this.count = 0;
    }

    /**
     * Gets the passive income generated by ChickenStrips.
     *
     * @return passive income generated by ChickenStrips
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of ChickenStrips.
     *
     * @param passive amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(final double passive) {
        this.passiveValue += passive;
    }

    /**
     * Sets the passive value of ChickenStrips.
     *
     * @param passiveValue new passive value of ChickenStrips
     */
    @Override
    public void setPassiveValue(final double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of ChickenStrips.
     *
     * @return cost of ChickenStrips
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of ChickenStrips.
     *
     * @param cost new cost of ChickenStrips
     */
    @Override
    public void setCost(final double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of ChickenStrips.
     *
     * @return number of ChickenStrips
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of ChickenStrips.
     *
     * @param count new number of ChickenStrips owned
     */
    @Override
    public void setCount(final int count) {
        this.count = count; }

    /**
     * Increments ChickenStrips count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}

