package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * Fries class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class Fries implements Item {
    /**
     * Initial cost of Fries.
     */
    static final int INITIAL_COST = 1000;
    private double cost;
    private double passiveValue;
    private int count;
    /**
     * Constructs an object of type Fries.
     */
    public Fries() {
        this.cost = INITIAL_COST;
        this.passiveValue = 0;
        this.count = 0;
    }

    /**
     * Gets the passive income generated by Fries.
     *
     * @return passive income generated by Fries
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of Fries.
     *
     * @param passive amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(final double passive) {
        this.passiveValue += passive;
    }

    /**
     * Sets the passive value of Fries.
     *
     * @param passiveValue new passive value of Fries
     */
    @Override
    public void setPassiveValue(final double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of Fries.
     *
     * @return cost of Fries
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of Fries.
     *
     * @param cost new cost of Fries
     */
    @Override
    public void setCost(final double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of Fries.
     *
     * @return number of Fries
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of Fries.
     *
     * @param count new number of Fries owned
     */
    @Override
    public void setCount(final int count) {
        this.count = count; }

    /**
     * Increments Fries count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}
