package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * Hotdog class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class HotDog implements Item {
    /**
     * Initial cost of HotDog.
     */
    static final int INITIAL_COST = 50;
    private double cost;
    private double passiveValue;
    private int count;
    /**
     * Constructs an object of type HotDog.
     */
    public HotDog() {
        this.count = 0;
        this.cost = INITIAL_COST;
        this.passiveValue = 0;
    }

    /**
     * Gets the passive income generated by HotDog.
     *
     * @return passive income generated by HotDog
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of HotDog.
     *
     * @param passiveValue amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(final double passiveValue) {
        this.passiveValue += passiveValue;
    }

    /**
     * Sets the passive value of HotDog.
     *
     * @param passiveValue new passive value of HotDog
     */
    @Override
    public void setPassiveValue(final double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of HotDog.
     *
     * @return cost of HotDog
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of HotDog.
     *
     * @param cost new cost of HotDog
     */
    @Override
    public void setCost(final double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of HotDog.
     *
     * @return number of HotDog
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of HotDog.
     *
     * @param count new number of HotDog owned
     */
    @Override
    public void setCount(final int count) {
        this.count = count; }

    /**
     * Increments HotDog count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}
