package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * Icecream class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class Icecream implements Item {
    /**
     * Initial cost of Icecream.
     */
    static final int INITIAL_COST = 1000000;
    private double cost;
    private double passiveValue;
    private int count;
    /**
     * Constructs an object of type Icecream.
     */
    public Icecream() {
        this.cost = INITIAL_COST;
        this.passiveValue = 0;
        this.count = 0;
    }

    /**
     * Gets the passive income generated by Icecream.
     *
     * @return passive income generated by Icecream
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of Icecream.
     *
     * @param passive amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(final double passive) {
        this.passiveValue += passive;
    }

    /**
     * Sets the passive value of Icecream.
     *
     * @param passiveValue new passive value of Icecream
     */
    @Override
    public void setPassiveValue(final double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of Icecream.
     *
     * @return cost of Icecream
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of Icecream.
     *
     * @param cost new cost of Icecream
     */
    @Override
    public void setCost(final double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of Icecream.
     *
     * @return number of Icecream
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of Icecream.
     *
     * @param count new number of Icecream owned
     */
    @Override
    public void setCount(final int count) {
        this.count = count; }

    /**
     * Increments Icecream count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}

