package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public interface Item {
    /**
     * Gets the passive income generated by Item.
     *
     * @return passive income generated by Item
     */
    double getPassiveIncome();

    /**
     * Increments passive value of Item.
     *
     * @param passiveValue amount to increment passive value by
     */
    void incrementPassiveValue(double passiveValue);
    /**
     * Sets the passive value of Item.
     *
     * @param passiveValue new passive value of Item
     */
    void setPassiveValue(double passiveValue);
    /**
     * Gets cost of Item.
     *
     * @return cost of Item
     */
    double getCost();
    /**
     * Sets cost of Item.
     *
     * @param cost new cost of Item
     */
    void setCost(double cost);
    /**
     * Gets number of Item.
     *
     * @return number of Item
     */
    int getCount();
    /**
     * Sets count of Item.
     *
     * @param count new number of Item owned
     */
    void setCount(int count);
    /**
     * Increments Item count by one.
     */
    void incrementCount();

}
