package ca.bcit.comp2522.termproject.comp2522202310termproject360;
/**
 * Pizza class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class Pizza implements Item {
    private double cost;
    private double passiveValue;
    private int count;

    /**
     * Constructs an object of type Pizza.
     */
    public Pizza() {
        this.cost = 10000;
        this.passiveValue = 0;
        this.count = 0;
    }

    /**
     * Gets the passive income generated by Pizza.
     *
     * @return passive income generated by Pizza
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of Pizza.
     *
     * @param passiveValue amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(double passiveValue) {
        this.passiveValue += passiveValue;
    }

    /**
     * Sets the passive value of Pizza.
     *
     * @param passiveValue new passive value of Pizza
     */
    @Override
    public void setPassiveValue(double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of Pizza.
     *
     * @return cost of Pizza
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of Pizza.
     *
     * @param cost new cost of Pizza
     */
    @Override
    public void setCost(double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of Pizza.
     *
     * @return number of Pizza
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of Pizza.
     *
     * @param count new number of Pizza owned
     */
    @Override
    public void setCount(int count) {this.count = count;}

    /**
     * Increments Pizza count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}
