package ca.bcit.comp2522.termproject.comp2522202310termproject360;

/**
 * Poutine class implements Item interface.
 *
 * @author Joshua Chuah & Justin Oh
 * @version 2023
 */
public class Poutine implements Item {
    /**
     * Initial cost of Poutine.
     */
    static final int INITIAL_COST = 100000;
    private double cost;
    private double passiveValue;
    private int count;

    /**
     * Constructs an object of type Poutine.
     */
    public Poutine() {
        this.cost = INITIAL_COST;
        this.passiveValue = 0;
        this.count = 0;
    }

    /**
     * Gets the passive income generated by Poutine.
     *
     * @return passive income generated by Poutine
     */
    @Override
    public double getPassiveIncome() {
        return this.passiveValue;
    }

    /**
     * Increments passive value of Poutine.
     *
     * @param passiveValue amount to increment passive value by
     */
    @Override
    public void incrementPassiveValue(final double passiveValue) {
        this.passiveValue += passiveValue;
    }

    /**
     * Sets the passive value of Poutine.
     *
     * @param passiveValue new passive value of Poutine
     */
    @Override
    public void setPassiveValue(final double passiveValue) {
        this.passiveValue = passiveValue;
    }

    /**
     * Gets cost of Poutine.
     *
     * @return cost of Poutine
     */
    @Override
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets cost of Poutine.
     *
     * @param cost new cost of Poutine
     */
    @Override
    public void setCost(final double cost) {
        this.cost = cost;
    }

    /**
     * Gets number of Poutine.
     *
     * @return number of Poutine
     */
    @Override
    public int getCount() {
        return this.count;
    }

    /**
     * Sets count of Poutine.
     *
     * @param count new number of Poutine owned
     */
    @Override
    public void setCount(final int count) {
        this.count = count; }

    /**
     * Increments Poutine count by one.
     */
    @Override
    public void incrementCount() {
        this.count++;
    }
}
